# Generated by Django 3.2.3 on 2021-06-18 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'body_part',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low'), ('MID', 'Mid'), ('HIGH', 'High')], max_length=5)),
                ('description', models.TextField()),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='studies', to='api.bodypart')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='studies', to='api.patient')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='studies', to='api.type')),
            ],
            options={
                'db_table': 'study',
            },
        ),
    ]
