# Generated by Django 3.2.3 on 2021-06-18 00:57

import logging

from django.db import migrations

logger = logging.getLogger('debug')


def populate_body_parts(apps, schema_editor):

    logger.warning(
        '[0002_populate_catalogs.py] List of body_parts is not complet.')
    BodyPart = apps.get_model('api', 'BodyPart')
    parts_list = ['STOMACH', 'NECK', 'CHEST', 'BREASTS']
    BodyPart.objects.bulk_create(
        [BodyPart(name=item) for item in parts_list])


def populate_types(apps, schema_editor):

    logger.warning(
        '[0002_populate_catalogs.py] List of body_parts is not complet.')
    Type = apps.get_model('api', 'Type')
    type_list = ['MAMMOGRAM', 'XRAY']
    Type.objects.bulk_create(
        [Type(name=item) for item in type_list])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_body_parts),
        migrations.RunPython(populate_types),
    ]
